services:
  - type: web
    name: equal-app
    runtime: node
    plan: starter
    branch: master
    buildCommand: npm ci && npm run build
    startCommand: node server.js
    nodeVersion: "20.11.0"
    envVars:
      - key: VITE_API_URL
        value: https://equal-backend.onrender.com/v1
      - key: VITE_WS_URL
        value: wss://equal-backend.onrender.com
